### ISSUE TITLE
Implement a controller component that will start the application under test

### ISSUE THREAD

**Issue by LyashenkoGS** [KissPeter/APIFuzzer#10]
The proper way to start an application under test is using a controller component. See http://kitty.readthedocs.io/en/latest/base_structure.html#controller 
Neet to implement a controller that will fork a process with the ingestion service on a free random port. After the service is up and running the controller should start fuzzing

**Comment by KissPeter** [comment]
I'm aware of this capability, but I don't plan to do this in the near future because it was planned to fuzz remote servers.

**Comment by KissPeter** [comment]
reflecting to my previous comment: It is planned for remote server fuzzing so won' be implemented
