### ISSUE TITLE
Protobuff support

### ISSUE THREAD

**Issue by LyashenkoGS** [KissPeter/APIFuzzer#11]
The fuzzer should generate proper request for the `application/x-protobuf `type

**Comment by KissPeter** [comment]
Does protobuf used in swagger? For me it seems it is beyond this project's scope

**Comment by LyashenkoGS** [comment]
Agree. 
Implementing schema unaware fuzzer will generate mostly invalid messages and will be inefficient even if the project will allow to pass a header `Content-type: application/x-protobuf` in requests . In other hand, add ing support to pass external protobuf schema and create dedicator mutator for protobuf probably outside of the project scope.
