### ISSUE TITLE
Create a "fuzzable" application

### ISSUE THREAD

**Issue by LyashenkoGS** [KissPeter/APIFuzzer#13]
Need to create a simple application or use existed one that :
* have simple business logic
* exposes REST API
* exposes documentation according to https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md
* have endpoints with different data types and content types (json, protobuff)

Currently, the https://github.com/LyashenkoGS/springboot_swagger_example/releases/tag/0.0.1-SNAPSHOT is used, so the application might be based on it.

**Comment by KissPeter** [comment]
I plan to introduce some functional testing. As part of that I will create some simple server where all the functionality can be tested

**Comment by KissPeter** [comment]
Done: https://github.com/KissPeter/APIFuzzer/blob/master/test/test_application.py

**Comment by lobax** [comment]
The swagger file referenced in the documentation (`test/test_swagger_definition.json`) is missing

**Comment by KissPeter** [comment]
Thanks, added
Péter
