### ISSUE TITLE
Package application

### ISSUE THREAD

**Issue by fkromer** [KissPeter/APIFuzzer#15]
Would be great to have a `setup.py` for the APIFuzzer to allow isntallation via `pip`... as intermediate step until #12.

**Comment by fkromer** [comment]
I created a docker image, refer to [Docker Hub](https://hub.docker.com/r/fkromer/apifuzzer/) and [GitHub](https://github.com/fkromer/docker-apifuzzer). (Considered sufficiently packaged until `setup.py` as part of #12 is provided.)

**Comment by KissPeter** [comment]
Thanks, however it needs to get it's cli parameters.
