### ISSUE TITLE
Question: How to interpret "!! Failure detected !!" in kitty log files

### ISSUE THREAD

**Issue by fkromer** [KissPeter/APIFuzzer#17]
Where can I find information about how to interpret `!! Failure detected !!` in kitty log files, e.g. `./kittylogs/kitty_20180314-114844.log`?

Relates to request and response logging: #4

**Comment by KissPeter** [comment]
Hi
It puts a json file into the directory configured with:
-r REPORT_DIR, --report_dir REPORT_DIR
                    Directory where error reports will be saved, default:   /tmp/
You can find the details in base64 encoded format
