### ISSUE TITLE
Retrieve swagger.json from a URL

### ISSUE THREAD

**Issue by LyashenkoGS** [KissPeter/APIFuzzer#18]
As a user,
I want to pass a path to swagger.json 
both as a file and as a URL

**Example:**
1. Passing swagger.json as a file(currently implemented)
 `fuzzer.py -s api-docs.json -u http://localhost:8080`
2. Passing swagger.json as a URL
 `fuzzer.py -s http://localhost:8080/v2/api-docs -u http://localhost:8080`

**Reasoning:**
This will allow to simplify integrating fuzzing in CI process by  removing intermediate step of persisting a swagger definition locally.

**Comment by KissPeter** [comment]
It is a good idea, I planned to do it at some point. 
First I would like to cover it with tests, create a pip package, introduce initial support of API Blueprint thenn extend it with functions like this.

Pull request is welcomed though :-)
