### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by lmcthbe** [KissPeter/APIFuzzer#41]
**Question**
Is HTTPS and oauth2 authorization supported?

Doing something like:

APIFuzzer --headers '[{"Authorization": "Bearer <token>"}]' -s openapi.yml -u https://<target>

**Comment by PeterKiss-Sophos** [comment]
Hi
yes

**Comment by KissPeter** [comment]
Hi,
you need to generate the token, but you can provide it to the fuzzer to use.
HTTPS is supported
Happy Fuzzing!
