### ISSUE TITLE
Copy/paste error in compile_base_url()

### ISSUE THREAD

**Issue by ngregoire** [KissPeter/APIFuzzer#42]
**Describe the bug**

Destination URL can't be extracted from OpenAPI definition files, because function compile_base_url() calls _compile_base_url_for_swagger() in all situations (probably a copy/paste error) https://github.com/KissPeter/APIFuzzer/blob/043ccd2b464fea178db58d2d7a235eead06b72e3/apifuzzer/openapi_template_generator.py#L260

**Executed command**

> APIFuzzer --src_url https://petstore3.swagger.io/api/v3/openapi.json

**APIFuzzer debug log**

> Unexpected exception happened during fuzz test preparation: 'schemes'. Feel free to report the issue

**Related API definition**

Publicly available at https://petstore3.swagger.io/api/v3/openapi.json

**Software environment (please complete the following information):**

 - OS: Ubuntu 20.4
-  Python version: 3.8.10
 - APIFuzzer Version: 0.9.9

**Comment by PeterKiss-Sophos** [comment]
Thanks for reporting this issue. I will take a look at it
