### ISSUE TITLE
--version not valid

### ISSUE THREAD

**Issue by aaronhmiller** [KissPeter/APIFuzzer#44]
**Describe the bug**
The -h options says both -v and --version should work, but only -v does. --version throws an error.

**APIFuzzer debug log**
```
# APIFuzzer --log debug --version
usage: APIFuzzer [-h] [-s SRC_FILE] [--src_url SRC_URL] [-r REPORT_DIR] [--level LEVEL] [-u ALTERNATE_URL] [-t TEST_RESULT_DST]
                 [--log {critical,fatal,error,warn,warning,info,debug,notset}] [--basic_output BASIC_OUTPUT] [--headers HEADERS]
                 [-v ,--version]
APIFuzzer: error: unrecognized arguments: --version
```

**Related API definition**
n/a

**Software environment (please complete the following information):**
 - OS: Docker 20.10.8 (running on Mac OS 11.6)
-  Python version: 3.9.7
 - APIFuzzer Version: 0.9.9

**Additional context**

**Comment by aaronhmiller** [comment]
dropped in PR https://github.com/KissPeter/APIFuzzer/pull/45 after testing locally.

**Comment by KissPeter** [comment]
Thanks @aaronhmiller  merged, closing this ticket
