### ISSUE TITLE
Correct headers and  path variables parsing

### ISSUE THREAD

**Issue by LyashenkoGS** [KissPeter/APIFuzzer#5]
* The fuzzer passes a Parameter Type: header as a GET parameter
* The fuzzer passes a Parameter Type: path as a GET parameter
**Expected:**
```
GET /product/show/l%D7x%26%B5%B8%C86%19%D4q%98 HTTP/1.1
someOptionalHeader:asd
Host: localhost:8080
Connection: keep-alive
Accept-Encoding: gzip, deflate
Accept: */*
User-Agent: python-requests/2.18.4
```

**Actual:** (provided by wireshark)
```
GET /product/show/%7Bid%7D?someOptionalHeader=asd&id=l%D7x%26%B5%B8%C86%19%D4q%98 HTTP/1.1
Host: localhost:8080
Connection: keep-alive
Accept-Encoding: gzip, deflate
Accept: */*
User-Agent: python-requests/2.18.4
```

**How to reproduce:**
Use https://github.com/LyashenkoGS/springboot_swagger_example/commit/13636377d2074755816f8fa1152c962ceb5e5d07
Build, run, export swagger.json according to the README.md

**Comment by KissPeter** [comment]
I've made some improvements on this area, could you please check it?

**Comment by LyashenkoGS** [comment]
Works fine in 9988388338f0e6116b4d1ec1d5acbb2a208ab28f
