### ISSUE TITLE
Report filenames start with -1

### ISSUE THREAD

**Issue by martinburchell** [KissPeter/APIFuzzer#52]
**Describe the bug**

The reports that get stored in the directory indicated by the `--report_dir` argument have filenames prefixed with the `current_index` on the model. `current_index` seems to start with -1 (a feature of `kittyfuzzer`?) so the first report is -1-something, the next 0-something and then 1-something. It would make more sense to me for the reports to begin with either 1 or 0. In addition, zero padding the filenames would make sorting by name consistent with the order in which the reports were created.

**Related API definition**

I assume any, but here's the one I was using

[api_schema.yaml.txt](https://github.com/KissPeter/APIFuzzer/files/8473679/api_schema.yaml.txt)

**Software environment (please complete the following information):**

- OS: Ubuntu 20.04
- Python version: 3.8
- APIFuzzer Version: Latest from GitHub

**Comment by KissPeter** [comment]
Hi,

Can you check https://github.com/KissPeter/APIFuzzer/tree/report_filename_improvement ?
Any PR is welcome
Péter

**Comment by martinburchell** [comment]
> Hi,
> 
> Can you check https://github.com/KissPeter/APIFuzzer/tree/report_filename_improvement ? Any PR is welcome Péter

Yes that looks good. I wasn't sure if current_index should start at -1 but that's down to kittyfuzzer.

**Comment by PeterKiss-Sophos** [comment]
Yes it is Kitty stuff.
I'm closing this ticket and this change will be in the next release. In the meantime you can get in from master
