### ISSUE TITLE
Unexpected exception happened during fuzz test preparation

### ISSUE THREAD

**Issue by DimaOwena** [KissPeter/APIFuzzer#55]
When running this command: 
**APIFuzzer -s /Users/username/Documents/demo.yaml**   

The result is: 
**Unexpected exception happened during fuzz test preparation: 'str' object has no attribute 'get'. Feel free to report the issue**

**Comment by KissPeter** [comment]
Please provide all the details expected in the issue template.
I am closing this one as important details are missing, but plese open a new one if you have everything 
Thank you
