### ISSUE TITLE
Cant shutdown the application via ctl+c on error

### ISSUE THREAD

**Issue by LyashenkoGS** [KissPeter/APIFuzzer#7]
**How to reproduce:**
run https://github.com/KissPeter/APIFuzzer/commit/dd38bcfb297a748b34927990952bcf9319eadbfe
against https://github.com/LyashenkoGS/springboot_swagger_example/commit/13636377d2074755816f8fa1152c962ceb5e5d07
**Actual behavior:**
After the error message, you can't close the application by pressing ctrl+c 
Tested on Ubuntu 16.04

/usr/bin/python2.7 /home/vagrant/APIFuzzer/fuzzer.py -s swagger.json -u http://localhost:8080
/product/show/{id}
get
id
someOptionalHeader
/product/delete/{id}
delete
id
someOptionalHeader
/product/list
get
someOptionalHeader
/product/add
post
product
someOptionalHeader
/product/update/{id}
put
id
product
someOptionalHeader
[INFO    ][base._load_session] No session loaded
[INFO    ][base._start_message] 
                 --------------------------------------------------
                 Starting fuzzing session
                 Target: FuzzerTarget
                 UI: WebInterface listening on 127.0.0.1:26000
                 Log: ./kittylogs/kitty_20180206-131801.log

                 Total possible mutation count: 720
                 --------------------------------------------------
                                 Happy hacking
                 --------------------------------------------------
            
[INFO    ][base.start] Performing environment test
[INFO    ][base._test_info] Current test: -1
[WARNING ][server_fuzzer._transmit] Exception occurred: field named (_product_show_{id}_GET|Template|default:0x2f70726f647563742f73686f772f7b69647d47455461736400) was not found in (params)
[WARNING ][server_fuzzer._transmit] Exception occurred: field named (_product_show_{id}_GET|Template|default:0x2f70726f647563742f73686f772f7b69647d47455461736400) was not found in (path_variables)
[ERROR   ][server_fuzzer._transmit] Error in transmit: 'NoneType' object has no attribute '__getitem__'
[INFO    ][server._test_environment] Environment test failed
[ERROR   ][base.start] Error occurred while fuzzing: TypeError("'NoneType' object has no attribute '__getitem__'",)
[ERROR   ][base.start] Traceback (most recent call last):
  File "/home/vagrant/.local/lib/python2.7/site-packages/kitty/fuzzers/base.py", line 384, in start
    self._test_environment()
  File "/home/vagrant/.local/lib/python2.7/site-packages/kitty/fuzzers/server.py", line 53, in _test_environment
    if self._run_sequence(sequence):
  File "/home/vagrant/.local/lib/python2.7/site-packages/kitty/fuzzers/server.py", line 74, in _run_sequence
    resp = self._transmit(node)
  File "/home/vagrant/APIFuzzer/apifuzzer/server_fuzzer.py", line 53, in _transmit
    return self.target.transmit(**payload)
  File "/home/vagrant/APIFuzzer/apifuzzer/fuzzer_target.py", line 50, in transmit
    kwargs['url'] = self.expand_path_variables(kwargs.get('path_variables'), kwargs['url'])
  File "/home/vagrant/APIFuzzer/apifuzzer/fuzzer_target.py", line 104, in expand_path_variables
    value = params[''.join(placeholder).decode('utf-8')]
TypeError: 'NoneType' object has no attribute '__getitem__'

**Comment by KissPeter** [comment]
It should be fixed now, could you please check it?

**Comment by LyashenkoGS** [comment]
The bug that causes the error has been fixed. But the issue is about shutting down the fuzzer correctly if it encountered an error via CTRL + C. Currently, you can shut down the fuzzer on error only via CTRL+Z.

**To reproduce:**
run 9988388338f0e6116b4d1ec1d5acbb2a208ab28f 
against LyashenkoGS/springboot_swagger_example@1363637
Then press CTRL+C during fuzzing

**Expected behavior** - the fuzzer shutdown with a stack trace
**Actual behavior** - the fuzzer is hanged with a stack trace and can't be shut down by pressing CTRL +C

**Comment by LyashenkoGS** [comment]
The same issue can be reproduced after fuzzing has been finished.

**Comment by KissPeter** [comment]
Sorry, I can't file swagger json in LyashenkoGS/springboot_swagger_example@1363637
Could you please add hints how to reproduce?
Thanks

**Comment by LyashenkoGS** [comment]
My bad.
[swagger.txt](https://github.com/KissPeter/APIFuzzer/files/2066356/swagger.txt)
Or you can get it  yourself:
* build and run the app https://github.com/LyashenkoGS/springboot_swagger_example/commit/1363637 
*  access http://localhost:8080/v2/api-docs
* save acquired JSON as swagger.json

**Comment by KissPeter** [comment]
I can't see this behavior any more
