### ISSUE TITLE
How to use --header correctly?

### ISSUE THREAD

**Issue by henning410** [KissPeter/APIFuzzer#72]
I try to use the option --header in `docker run `. 
However, I always get error messages like: 

`APIFuzzer: error: argument --headers: ('%s is not JSON', '[{"Authorization":')`

I tried different formats such as: 
`--headers {"Authorization": 'Bearer 1234'}`

`--headers {"Authorization": "Bearer 1234"}`

`--headers [{"Authorization": "Bearer 1234"}]`

`--headers '{"Authorization": "Bearer 1234"}'`

`--headers '[{"Authorization": "Bearer 1234"}]'`

but always get some error message. 
Can you tell my how to do this correctly? Maybe you can add some example to your README

**Comment by KissPeter** [comment]
Hi
https://github.com/KissPeter/APIFuzzer/blob/master/README.md#quick-start contains an example:
`  --headers HEADERS     Http request headers added to all request. Example: '[{"Authorization": "SuperSecret"}, {"Auth2": "asd"}]'
`
This looks good to me:
`--headers '[{"Authorization": "Bearer 1234"}]'`

**Comment by KissPeter** [comment]
If this is only in Docker, you might want to check https://github.com/KissPeter/APIFuzzer/issues/64
