### ISSUE TITLE
Pass authorization header as command line parameters

### ISSUE THREAD

**Issue by LyashenkoGS** [KissPeter/APIFuzzer#9]
As a user, I want to pass authorization headers that will be used with each request
as command line parameters. Assumed that credentials will be stored in a CI server and passed as environment variables.

Example:
`python fuzzer.py -s your_swagger_definition.json -u http://localhost:8080/ --headers {"authorization": 'Bearer an-authorization-token', "authorization-claims": 'azazadsfdsf'}`

**Comment by KissPeter** [comment]
Ready
